### ISSUE TITLE
FlatUi fails to build on Ubuntu 17.04

### ISSUE THREAD

**Issue by giellamo** [google/flatui#14]
commit 8746f609175e6689065bccdc27be86285a41f1e2

a whole bunch of

[ 85%] Building CXX object obj/fplbase/CMakeFiles/fplbase.dir/src/main.cpp.o
/home/giellamo/projects/flatui/dependencies/stb/stb_image.h: In function ‘int stbi__create_png_image_raw(stbi__png*, stbi_uc*, stbi__uint32, int, stbi__uint32, stbi__uint32, int, int)’:
/home/giellamo/projects/flatui/dependencies/stb/stb_image.h:4086:17: error: this ‘for’ clause does not guard... **[-Werror=misleading-indentation]**
                 for (k=0; k < nk; ++k)
                 ^
/home/giellamo/projects/flatui/dependencies/stb/stb_image.h:4090:13: note: in expansion of macro ‘CASE’
